spring:
  datasource:
    username: postgres
    password: stagiu
    url: "jdbc:postgresql://localhost:5432/pentastagiu2021java"
  jpa:
    //sa stie cum sa transforme entitatile noastre in cod - dialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      // sa mi faca update fara sa mai fac eu de mana, face el automat
      ddl-auto: update